// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VOD.Film.Data.DataAccess;

#nullable disable

namespace VOD.Film.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "James Cameron"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Martin Scorsese"
                        });
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.FilmGenre", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("FilmId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("FilmGenres");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            FilmId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            FilmId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            FilmId = 4,
                            GenreId = 3
                        },
                        new
                        {
                            FilmId = 4,
                            GenreId = 4
                        },
                        new
                        {
                            FilmId = 5,
                            GenreId = 5
                        },
                        new
                        {
                            FilmId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            FilmId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            FilmId = 7,
                            GenreId = 1
                        },
                        new
                        {
                            FilmId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            FilmId = 8,
                            GenreId = 5
                        },
                        new
                        {
                            FilmId = 8,
                            GenreId = 1
                        },
                        new
                        {
                            FilmId = 9,
                            GenreId = 3
                        },
                        new
                        {
                            FilmId = 10,
                            GenreId = 4
                        },
                        new
                        {
                            FilmId = 11,
                            GenreId = 2
                        },
                        new
                        {
                            FilmId = 11,
                            GenreId = 4
                        },
                        new
                        {
                            FilmId = 12,
                            GenreId = 2
                        },
                        new
                        {
                            FilmId = 12,
                            GenreId = 5
                        },
                        new
                        {
                            FilmId = 13,
                            GenreId = 3
                        },
                        new
                        {
                            FilmId = 13,
                            GenreId = 1
                        });
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.FilmModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<string>("FilmPosterUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FilmUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("Free")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Released")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
                            DirectorId = 1,
                            FilmPosterUrl = "https://i.ebayimg.com/images/g/CwEAAOSwv4xf5cdv/s-l1600.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=5PSNL1qE6VY",
                            Free = true,
                            Released = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.",
                            DirectorId = 2,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=EXeTwQWrcwY",
                            Free = false,
                            Released = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Description = "During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.",
                            DirectorId = 3,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=lc0UehYemQA",
                            Free = true,
                            Released = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            DirectorId = 3,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=NmzuHjWmXOc",
                            Free = false,
                            Released = new DateTime(1994, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            DirectorId = 1,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=UaVTIH8mujA",
                            Free = false,
                            Released = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
                            DirectorId = 2,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=YoHD9XEInc0",
                            Free = false,
                            Released = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
                            DirectorId = 4,
                            FilmPosterUrl = "https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=TEN-2uTi2c0",
                            Free = false,
                            Released = new DateTime(1957, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "12 Angry Men"
                        },
                        new
                        {
                            Id = 8,
                            Description = "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazi Germans.",
                            DirectorId = 5,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=gG22XNhtnoY",
                            Free = false,
                            Released = new DateTime(1993, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            DirectorId = 5,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
                            Free = false,
                            Released = new DateTime(2003, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            DirectorId = 4,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
                            Free = false,
                            Released = new DateTime(1994, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
                            DirectorId = 1,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=IFNUGzCOQoI",
                            Free = false,
                            Released = new DateTime(1966, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Good, the Bad and the Ugly"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.",
                            DirectorId = 2,
                            FilmPosterUrl = "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=bLvqoHBptjg",
                            Free = false,
                            Released = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forest Gump"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
                            DirectorId = 5,
                            FilmPosterUrl = "https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg",
                            FilmUrl = "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
                            Free = false,
                            Released = new DateTime(1990, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Goodfellas"
                        });
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Crime"
                        });
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.SimilarFilmModel", b =>
                {
                    b.Property<int>("ParentFilmId")
                        .HasColumnType("int");

                    b.Property<int>("SimilarFilmId")
                        .HasColumnType("int");

                    b.HasKey("ParentFilmId", "SimilarFilmId");

                    b.HasIndex("SimilarFilmId");

                    b.ToTable("SimilarFilms");

                    b.HasData(
                        new
                        {
                            ParentFilmId = 1,
                            SimilarFilmId = 2
                        },
                        new
                        {
                            ParentFilmId = 1,
                            SimilarFilmId = 4
                        },
                        new
                        {
                            ParentFilmId = 2,
                            SimilarFilmId = 3
                        },
                        new
                        {
                            ParentFilmId = 3,
                            SimilarFilmId = 1
                        },
                        new
                        {
                            ParentFilmId = 4,
                            SimilarFilmId = 5
                        },
                        new
                        {
                            ParentFilmId = 5,
                            SimilarFilmId = 11
                        },
                        new
                        {
                            ParentFilmId = 5,
                            SimilarFilmId = 6
                        },
                        new
                        {
                            ParentFilmId = 11,
                            SimilarFilmId = 4
                        },
                        new
                        {
                            ParentFilmId = 4,
                            SimilarFilmId = 7
                        },
                        new
                        {
                            ParentFilmId = 5,
                            SimilarFilmId = 8
                        },
                        new
                        {
                            ParentFilmId = 6,
                            SimilarFilmId = 5
                        },
                        new
                        {
                            ParentFilmId = 13,
                            SimilarFilmId = 5
                        },
                        new
                        {
                            ParentFilmId = 13,
                            SimilarFilmId = 4
                        });
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.FilmGenre", b =>
                {
                    b.HasOne("VOD.Film.Data.Entities.Models.FilmModel", "Film")
                        .WithMany("FilmGenres")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VOD.Film.Data.Entities.Models.Genre", "Genre")
                        .WithMany("FilmGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.FilmModel", b =>
                {
                    b.HasOne("VOD.Film.Data.Entities.Models.Director", "Director")
                        .WithMany("Film")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.SimilarFilmModel", b =>
                {
                    b.HasOne("VOD.Film.Data.Entities.Models.FilmModel", "ParentFilm")
                        .WithMany("SimilarFilms")
                        .HasForeignKey("ParentFilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VOD.Film.Data.Entities.Models.FilmModel", "SimilarFilm")
                        .WithMany()
                        .HasForeignKey("SimilarFilmId")
                        .IsRequired();

                    b.Navigation("ParentFilm");

                    b.Navigation("SimilarFilm");
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.Director", b =>
                {
                    b.Navigation("Film");
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.FilmModel", b =>
                {
                    b.Navigation("FilmGenres");

                    b.Navigation("SimilarFilms");
                });

            modelBuilder.Entity("VOD.Film.Data.Entities.Models.Genre", b =>
                {
                    b.Navigation("FilmGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
